### ISSUE TITLE
Add yamllint to pre-commit-config.yaml

### ISSUE THREAD

**Issue by dougthor42** [dougthor42/_template_python#16]
The template already has a .yamllint file, now we need to add yamllint to the pre-commit config.

```
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.20.0
    hooks:
      - id: yamllint
        name: Yaml Lint
        verbose: true
```
